services:
  - type: web
    name: fraud-detection-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com your-frontend-url.vercel.app"
      - key: DATABASE_URL
        fromDatabase:
          name: fraud-db
          property: connectionString